//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class bfiamu
    {
        public decimal uid { get; set; }
        public System.DateTime data_date { get; set; }
        public string index_name { get; set; }
        public Nullable<long> deal_stock_cnt { get; set; }
        public Nullable<decimal> deal_money { get; set; }
        public Nullable<int> deal_trade_cnt { get; set; }
        public Nullable<decimal> up_down_price { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    }
}
