//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_market_highlight
    {
        public decimal Uid { get; set; }
        public System.DateTime data_date { get; set; }
        public Nullable<int> list_stock_count { get; set; }
        public Nullable<decimal> total_capital { get; set; }
        public Nullable<decimal> total_value { get; set; }
        public Nullable<decimal> today_trade_value { get; set; }
        public Nullable<decimal> today_trade_stock_count { get; set; }
        public Nullable<decimal> close_index_price { get; set; }
        public Nullable<int> up_count { get; set; }
        public Nullable<int> down_count { get; set; }
        public Nullable<int> no_change_count { get; set; }
        public Nullable<decimal> index_up_down_price { get; set; }
        public Nullable<int> up_limit_count { get; set; }
        public Nullable<int> down_limit_count { get; set; }
        public Nullable<int> no_trade_count { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
