//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_qfii
    {
        public decimal Uid { get; set; }
        public System.DateTime data_date { get; set; }
        public int rank { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public Nullable<long> issue_stock_count { get; set; }
        public Nullable<long> remain_invest_count { get; set; }
        public Nullable<long> hold_count { get; set; }
        public Nullable<decimal> remain_invest_percent { get; set; }
        public Nullable<decimal> hold_percent { get; set; }
        public Nullable<decimal> law_hold_limit { get; set; }
        public string data_note { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
