//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_index_all
    {
        public decimal uid { get; set; }
        public System.DateTime data_date { get; set; }
        public string select_type { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public Nullable<decimal> deal_stock_num { get; set; }
        public Nullable<decimal> deal_trade_num { get; set; }
        public Nullable<decimal> deal_money { get; set; }
        public Nullable<decimal> open_price { get; set; }
        public Nullable<decimal> high_price { get; set; }
        public Nullable<decimal> low_price { get; set; }
        public Nullable<decimal> close_price { get; set; }
        public Nullable<sbyte> up_down { get; set; }
        public Nullable<decimal> up_down_price { get; set; }
        public Nullable<decimal> last_show_buy_price { get; set; }
        public Nullable<decimal> last_show_buy_qty { get; set; }
        public Nullable<decimal> last_show_sell_price { get; set; }
        public Nullable<decimal> last_show_sell_qty { get; set; }
        public Nullable<decimal> eps { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
