//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class mi_qfiis
    {
        public decimal uid { get; set; }
        public System.DateTime data_date { get; set; }
        public string select_type { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public string world_stock_no { get; set; }
        public Nullable<long> issue_cnt { get; set; }
        public Nullable<long> investable_cnt { get; set; }
        public Nullable<long> hold_cnt { get; set; }
        public Nullable<decimal> investable_rate { get; set; }
        public Nullable<decimal> hold_rate { get; set; }
        public Nullable<decimal> law_max_rate { get; set; }
        public Nullable<decimal> law_china_max_rate { get; set; }
        public string change_reason { get; set; }
        public Nullable<System.DateTime> last_report_change_date { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
