//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_filter_stg
    {
        public decimal uid { get; set; }
        public string stg_code { get; set; }
        public string stg_name { get; set; }
        public string stg_class_name { get; set; }
        public string stg_p1 { get; set; }
        public string stg_p2 { get; set; }
        public string stg_p3 { get; set; }
        public string stg_p4 { get; set; }
        public string stg_p5 { get; set; }
        public string stg_p6 { get; set; }
        public string stg_p7 { get; set; }
        public string stg_p8 { get; set; }
        public string stg_p9 { get; set; }
        public string stg_p10 { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
