//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class t86
    {
        public decimal uid { get; set; }
        public System.DateTime data_date { get; set; }
        public string select_type { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public Nullable<long> foreign_buy_in { get; set; }
        public Nullable<long> foreign_sell_out { get; set; }
        public Nullable<long> foreign_diff { get; set; }
        public Nullable<long> foreign_dealer_buy_in { get; set; }
        public Nullable<long> foreign_dealer_sell_out { get; set; }
        public Nullable<long> foreign_dealer_diff { get; set; }
        public Nullable<long> trust_buy_in { get; set; }
        public Nullable<long> trust_sell_out { get; set; }
        public Nullable<long> trust_diff { get; set; }
        public Nullable<long> dealer_diff { get; set; }
        public Nullable<long> dealer_self_buy_in { get; set; }
        public Nullable<long> dealer_self_sell_out { get; set; }
        public Nullable<long> dealer_self_diff { get; set; }
        public Nullable<long> dealer_risk_buy_in { get; set; }
        public Nullable<long> dealer_risk_sell_out { get; set; }
        public Nullable<long> dealer_risk_diff { get; set; }
        public Nullable<long> capital3_total_diff { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
