//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TwStockDataContext : DbContext
    {
        public TwStockDataContext()
            : base("name=TwStockDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bfi84u2> bfi84u2 { get; set; }
        public virtual DbSet<bfiamu> bfiamu { get; set; }
        public virtual DbSet<bfiauu_daily> bfiauu_daily { get; set; }
        public virtual DbSet<bfiauu_monthly> bfiauu_monthly { get; set; }
        public virtual DbSet<bfiauu_single> bfiauu_single { get; set; }
        public virtual DbSet<bfiauu_stock> bfiauu_stock { get; set; }
        public virtual DbSet<bfiauu_yearly> bfiauu_yearly { get; set; }
        public virtual DbSet<bft41u> bft41u { get; set; }
        public virtual DbSet<bwibbu_daily> bwibbu_daily { get; set; }
        public virtual DbSet<fmnptk> fmnptk { get; set; }
        public virtual DbSet<fmnptk_stat> fmnptk_stat { get; set; }
        public virtual DbSet<fmsrfk> fmsrfk { get; set; }
        public virtual DbSet<fmtqik> fmtqik { get; set; }
        public virtual DbSet<mi_5mins> mi_5mins { get; set; }
        public virtual DbSet<mi_index> mi_index { get; set; }
        public virtual DbSet<mi_index_all> mi_index_all { get; set; }
        public virtual DbSet<mi_index_deal_stat> mi_index_deal_stat { get; set; }
        public virtual DbSet<mi_index_etf> mi_index_etf { get; set; }
        public virtual DbSet<mi_index_intrust_stat> mi_index_intrust_stat { get; set; }
        public virtual DbSet<mi_index_market_stat> mi_index_market_stat { get; set; }
        public virtual DbSet<mi_index_price_idx_cross> mi_index_price_idx_cross { get; set; }
        public virtual DbSet<mi_index_price_idx_twcomp> mi_index_price_idx_twcomp { get; set; }
        public virtual DbSet<mi_index_price_idx_twse> mi_index_price_idx_twse { get; set; }
        public virtual DbSet<mi_index_return_idx_cross> mi_index_return_idx_cross { get; set; }
        public virtual DbSet<mi_index_return_idx_twcomp> mi_index_return_idx_twcomp { get; set; }
        public virtual DbSet<mi_index_return_idx_twse> mi_index_return_idx_twse { get; set; }
        public virtual DbSet<mi_index_top20> mi_index_top20 { get; set; }
        public virtual DbSet<mi_index_up_down_stat> mi_index_up_down_stat { get; set; }
        public virtual DbSet<mi_margin> mi_margin { get; set; }
        public virtual DbSet<mi_margin_stat> mi_margin_stat { get; set; }
        public virtual DbSet<mi_qfiis_cat> mi_qfiis_cat { get; set; }
        public virtual DbSet<mi_qfiis_sort_20> mi_qfiis_sort_20 { get; set; }
        public virtual DbSet<stock_day> stock_day { get; set; }
        public virtual DbSet<stock_day_avg> stock_day_avg { get; set; }
        public virtual DbSet<stock_first> stock_first { get; set; }
        public virtual DbSet<stock_item> stock_item { get; set; }
        public virtual DbSet<t86> t86 { get; set; }
        public virtual DbSet<twt38u> twt38u { get; set; }
        public virtual DbSet<twt43u> twt43u { get; set; }
        public virtual DbSet<twt44u> twt44u { get; set; }
        public virtual DbSet<twt47u> twt47u { get; set; }
        public virtual DbSet<twt54u> twt54u { get; set; }
        public virtual DbSet<twt84u> twt84u { get; set; }
        public virtual DbSet<twt92u> twt92u { get; set; }
        public virtual DbSet<twt93u> twt93u { get; set; }
        public virtual DbSet<twta1u> twta1u { get; set; }
        public virtual DbSet<twtasu> twtasu { get; set; }
        public virtual DbSet<twtb4u> twtb4u { get; set; }
        public virtual DbSet<twtb4u_stat> twtb4u_stat { get; set; }
        public virtual DbSet<twtbau2> twtbau2 { get; set; }
        public virtual DbSet<d_3itrdsum_daily> d_3itrdsum_daily { get; set; }
        public virtual DbSet<bfi82u_daily> bfi82u_daily { get; set; }
        public virtual DbSet<bfi82u_month> bfi82u_month { get; set; }
        public virtual DbSet<bfi82u_week> bfi82u_week { get; set; }
        public virtual DbSet<mi_qfiis> mi_qfiis { get; set; }
        public virtual DbSet<d_3itrade_hedge_daily> d_3itrade_hedge_daily { get; set; }
        public virtual DbSet<d_dealtr_hedge_daily> d_dealtr_hedge_daily { get; set; }
        public virtual DbSet<d_margin_bal> d_margin_bal { get; set; }
        public virtual DbSet<d_stk_quote> d_stk_quote { get; set; }
        public virtual DbSet<d_index_summary> d_index_summary { get; set; }
        public virtual DbSet<d_market_highlight> d_market_highlight { get; set; }
        public virtual DbSet<d_market_statistics_daily> d_market_statistics_daily { get; set; }
        public virtual DbSet<d_stk_wn1430> d_stk_wn1430 { get; set; }
        public virtual DbSet<d_stk_wn1430_summary> d_stk_wn1430_summary { get; set; }
        public virtual DbSet<d_sitctr_daily> d_sitctr_daily { get; set; }
        public virtual DbSet<d_forgtr_daily> d_forgtr_daily { get; set; }
        public virtual DbSet<d_qfiisect> d_qfiisect { get; set; }
        public virtual DbSet<d_qfii> d_qfii { get; set; }
        public virtual DbSet<d_block_day> d_block_day { get; set; }
        public virtual DbSet<d_mkt> d_mkt { get; set; }
        public virtual DbSet<d_rt_brk> d_rt_brk { get; set; }
        public virtual DbSet<d_sectr> d_sectr { get; set; }
        public virtual DbSet<d_pera> d_pera { get; set; }
        public virtual DbSet<d_shtsell> d_shtsell { get; set; }
        public virtual DbSet<d_peratio_pera> d_peratio_pera { get; set; }
        public virtual DbSet<d_trn_daily> d_trn_daily { get; set; }
        public virtual DbSet<d_vol_rank_daily> d_vol_rank_daily { get; set; }
        public virtual DbSet<d_amt_rank_daily> d_amt_rank_daily { get; set; }
        public virtual DbSet<d_stk_avg_daily> d_stk_avg_daily { get; set; }
        public virtual DbSet<d_avg_amt_daily> d_avg_amt_daily { get; set; }
        public virtual DbSet<d_rt_rally_daily> d_rt_rally_daily { get; set; }
        public virtual DbSet<d_rt_declined_daily> d_rt_declined_daily { get; set; }
        public virtual DbSet<p_filter_stg_describe> p_filter_stg_describe { get; set; }
        public virtual DbSet<p_filter_stg> p_filter_stg { get; set; }
        public virtual DbSet<d_margin_sbl> d_margin_sbl { get; set; }
        public virtual DbSet<d_mgused_daily> d_mgused_daily { get; set; }
    }
}
