//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class twt84u
    {
        public decimal uid { get; set; }
        public string select_type { get; set; }
        public System.DateTime data_date { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public Nullable<decimal> today_high_limit { get; set; }
        public Nullable<decimal> today_open_base { get; set; }
        public Nullable<decimal> today_low_limit { get; set; }
        public Nullable<decimal> yesterday_open_base { get; set; }
        public Nullable<decimal> yesterday_close { get; set; }
        public Nullable<decimal> yesterday_buy_in { get; set; }
        public Nullable<decimal> yesterday_sell_out { get; set; }
        public Nullable<System.DateTime> recent_deal_date { get; set; }
        public string can_odd_lot { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
