//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwStockGrabBLL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class twta1u
    {
        public decimal uid { get; set; }
        public System.DateTime data_date { get; set; }
        public string select_type { get; set; }
        public string stock_no { get; set; }
        public string stock_name { get; set; }
        public string market_type { get; set; }
        public Nullable<decimal> finance_yesterday_balance { get; set; }
        public Nullable<decimal> finance_buy_in { get; set; }
        public Nullable<decimal> finance_sell_out { get; set; }
        public Nullable<decimal> finance_cash_back { get; set; }
        public Nullable<decimal> finance_today_balance { get; set; }
        public Nullable<decimal> finance_ceiling { get; set; }
        public Nullable<decimal> dealer_yesterday_balance { get; set; }
        public Nullable<decimal> dealer_buy_in { get; set; }
        public Nullable<decimal> dealer_sell_out { get; set; }
        public Nullable<decimal> dealer_cash_back { get; set; }
        public Nullable<decimal> dealer_change { get; set; }
        public Nullable<decimal> dealer_today_balance { get; set; }
        public Nullable<decimal> dealer_ceiling { get; set; }
        public Nullable<decimal> dealer_unlimit_yesterday_balance { get; set; }
        public Nullable<decimal> dealer_unlimit_buy_in { get; set; }
        public Nullable<decimal> dealer_unlimit_sell_out { get; set; }
        public Nullable<decimal> dealer_unlimit_cash_back { get; set; }
        public Nullable<decimal> dealer_unlimit_change { get; set; }
        public Nullable<decimal> dealer_unlimit_today_balance { get; set; }
        public Nullable<decimal> dealer_unlimit_ceiling { get; set; }
        public Nullable<decimal> margin_loan_yesterday_balance { get; set; }
        public Nullable<decimal> margin_loan_buy_in { get; set; }
        public Nullable<decimal> margin_loan_sell_out { get; set; }
        public Nullable<decimal> margin_loan_cash_back { get; set; }
        public Nullable<decimal> margin_loan_change { get; set; }
        public Nullable<decimal> margin_loan_today_balance { get; set; }
        public Nullable<decimal> margin_loan_ceiling { get; set; }
        public Nullable<decimal> margin_deliver_yesterday_balance { get; set; }
        public Nullable<decimal> margin_deliver_buy_in { get; set; }
        public Nullable<decimal> margin_deliver_sell_out { get; set; }
        public Nullable<decimal> margin_deliver_cash_back { get; set; }
        public Nullable<decimal> margin_deliver_change { get; set; }
        public Nullable<decimal> margin_deliver_today_balance { get; set; }
        public Nullable<decimal> margin_deliver_ceiling { get; set; }
        public string note { get; set; }
        public string title { get; set; }
        public System.DateTime create_at { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
